<?xml version='1.0' encoding='ISO-8859-1'?>
<?xml-stylesheet href="ponctualite-mensuelle-transilien.css"  type="text/css"?>
pwd
pwd<!DOCTYPE Services [<!ELEMENT Services (Service+)><!ELEMENT Service (Nom, Lignes)><!ELEMENT Lignes (Ligne+)><!ELEMENT Ligne (ID, Nom, Train)><!ELEMENT Train (ID, Ponctualites)><!ELEMENT Ponctualites (Entete, Ponctualite+)><!ELEMENT Entete (Date, Taux, PonctuelParRetard)><!ELEMENT Ponctualite (Date, Taux, PonctuelParRetard)><!ELEMENT Nom (#PCDATA)><!ELEMENT ID (#PCDATA)><!ELEMENT Date (#PCDATA)><!ELEMENT Taux (#PCDATA)><!ELEMENT PonctuelParRetard (#PCDATA)>]>
<Services><Service><Nom>RER</Nom><Lignes><Ligne><ID>A</ID><Nom>RER A</Nom><Train><ID>TRA_1</ID><Ponctualites><Entete><Date>Date</Date><Taux>Taux de ponctualité</Taux><PonctuelParRetard>Nombre de voyageurs à l'heure pour un voyageur en retard</PonctuelParRetard></Entete><Ponctualite><Date>2013-01</Date><Taux>83.6</Taux><PonctuelParRetard>5.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-04</Date><Taux>83.3</Taux><PonctuelParRetard>5.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-08</Date><Taux>88.9</Taux><PonctuelParRetard>8.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-02</Date><Taux>85.7</Taux><PonctuelParRetard>6.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-02</Date><Taux>73.0954862767</Taux><PonctuelParRetard>2.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-03</Date><Taux>71.9550770992</Taux><PonctuelParRetard>2.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-06</Date><Taux>71.1496303121</Taux><PonctuelParRetard>2.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-09</Date><Taux>83.3</Taux><PonctuelParRetard>5.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-11</Date><Taux>80.9</Taux><PonctuelParRetard>4.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-05</Date><Taux>87.6</Taux><PonctuelParRetard>7.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-10</Date><Taux>68.8</Taux><PonctuelParRetard>2.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-11</Date><Taux>69.8</Taux><PonctuelParRetard>2.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-04</Date><Taux>71.9766560096</Taux><PonctuelParRetard>2.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-08</Date><Taux>82.9967982302</Taux><PonctuelParRetard>4.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-02</Date><Taux>86.2</Taux><PonctuelParRetard>6.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-06</Date><Taux>83.4</Taux><PonctuelParRetard>5.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-12</Date><Taux>81.2</Taux><PonctuelParRetard>4.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-01</Date><Taux>81.1</Taux><PonctuelParRetard>4.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-04</Date><Taux>85.7</Taux><PonctuelParRetard>6.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-06</Date><Taux>72.6</Taux><PonctuelParRetard>2.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-07</Date><Taux>70.5</Taux><PonctuelParRetard>2.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-08</Date><Taux>81.2</Taux><PonctuelParRetard>4.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-07</Date><Taux>83.2</Taux><PonctuelParRetard>5.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-03</Date><Taux>83.3</Taux><PonctuelParRetard>5.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-05</Date><Taux>71.2171208681</Taux><PonctuelParRetard>2.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-03</Date><Taux>84.0</Taux><PonctuelParRetard>5.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-05</Date><Taux>86.4</Taux><PonctuelParRetard>6.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-10</Date><Taux>83.1</Taux><PonctuelParRetard>4.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-09</Date><Taux>70.9</Taux><PonctuelParRetard>2.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-12</Date><Taux>67.3</Taux><PonctuelParRetard>2.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-01</Date><Taux>74.5</Taux><PonctuelParRetard>2.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-07</Date><Taux>73.1</Taux><PonctuelParRetard>2.7</PonctuelParRetard></Ponctualite></Ponctualites></Train></Ligne><Ligne><ID>B</ID><Nom>RER B</Nom><Train><ID>TRA_2</ID><Ponctualites><Entete><Date>Date</Date><Taux>Taux de ponctualité</Taux><PonctuelParRetard>Nombre de voyageurs à l'heure pour un voyageur en retard</PonctuelParRetard></Entete><Ponctualite><Date>2013-02</Date><Taux>80.3</Taux><PonctuelParRetard>4.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-08</Date><Taux>89.9</Taux><PonctuelParRetard>8.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-09</Date><Taux>86.6</Taux><PonctuelParRetard>6.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-03</Date><Taux>87.9</Taux><PonctuelParRetard>7.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-07</Date><Taux>86.9</Taux><PonctuelParRetard>6.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-04</Date><Taux>86.1725099925</Taux><PonctuelParRetard>6.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-07</Date><Taux>90.9</Taux><PonctuelParRetard>10.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-11</Date><Taux>77.9</Taux><PonctuelParRetard>3.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-04</Date><Taux>88.5</Taux><PonctuelParRetard>7.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-06</Date><Taux></Taux><PonctuelParRetard>0.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-09</Date><Taux>87.4</Taux><PonctuelParRetard>6.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-02</Date><Taux>85.3965470191</Taux><PonctuelParRetard>5.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-05</Date><Taux>86.9952922687</Taux><PonctuelParRetard>6.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-06</Date><Taux>84.9707913192</Taux><PonctuelParRetard>5.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-07</Date><Taux>84.1</Taux><PonctuelParRetard>5.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-01</Date><Taux>81.3</Taux><PonctuelParRetard>4.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-02</Date><Taux>88.9</Taux><PonctuelParRetard>8.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-05</Date><Taux>89.4</Taux><PonctuelParRetard>8.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-08</Date><Taux>90.7</Taux><PonctuelParRetard>9.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-10</Date><Taux>85.5</Taux><PonctuelParRetard>5.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-11</Date><Taux>86.1</Taux><PonctuelParRetard>6.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-12</Date><Taux>84.6</Taux><PonctuelParRetard>5.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-01</Date><Taux>88.5</Taux><PonctuelParRetard>7.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-03</Date><Taux>89.8537787545</Taux><PonctuelParRetard>8.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-08</Date><Taux>92.9183310249</Taux><PonctuelParRetard>13.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-03</Date><Taux>82.7</Taux><PonctuelParRetard>4.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-04</Date><Taux>86.4</Taux><PonctuelParRetard>6.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-10</Date><Taux>80.7</Taux><PonctuelParRetard>4.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-01</Date><Taux>80.1</Taux><PonctuelParRetard>4.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-05</Date><Taux>84.0</Taux><PonctuelParRetard>5.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-06</Date><Taux>82.2</Taux><PonctuelParRetard>4.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-12</Date><Taux>82.4</Taux><PonctuelParRetard>4.7</PonctuelParRetard></Ponctualite></Ponctualites></Train></Ligne><Ligne><ID>D</ID><Nom>RER D</Nom><Train><ID>TRA_4</ID><Ponctualites><Entete><Date>Date</Date><Taux>Taux de ponctualité</Taux><PonctuelParRetard>Nombre de voyageurs à l'heure pour un voyageur en retard</PonctuelParRetard></Entete><Ponctualite><Date>2013-03</Date><Taux>80.0</Taux><PonctuelParRetard>4.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-01</Date><Taux>86.0</Taux><PonctuelParRetard>6.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-02</Date><Taux>88.2</Taux><PonctuelParRetard>7.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-07</Date><Taux>86.6</Taux><PonctuelParRetard>6.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-10</Date><Taux>81.4</Taux><PonctuelParRetard>4.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-01</Date><Taux>86.562984012</Taux><PonctuelParRetard>6.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-07</Date><Taux>87.7</Taux><PonctuelParRetard>7.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-01</Date><Taux>77.6</Taux><PonctuelParRetard>3.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-05</Date><Taux>87.1</Taux><PonctuelParRetard>6.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-09</Date><Taux>83.1</Taux><PonctuelParRetard>4.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-05</Date><Taux>86.3768853161</Taux><PonctuelParRetard>6.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-08</Date><Taux>90.4</Taux><PonctuelParRetard>9.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-10</Date><Taux>79.6</Taux><PonctuelParRetard>3.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-05</Date><Taux>85.9</Taux><PonctuelParRetard>6.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-08</Date><Taux>92.0</Taux><PonctuelParRetard>11.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-09</Date><Taux>87.0</Taux><PonctuelParRetard>6.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-06</Date><Taux>82.8097061383</Taux><PonctuelParRetard>4.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-08</Date><Taux>91.5</Taux><PonctuelParRetard>10.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-02</Date><Taux>79.3</Taux><PonctuelParRetard>3.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-04</Date><Taux>82.9</Taux><PonctuelParRetard>4.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-06</Date><Taux>85.1</Taux><PonctuelParRetard>5.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-12</Date><Taux>85.5</Taux><PonctuelParRetard>5.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-02</Date><Taux>87.642140672</Taux><PonctuelParRetard>7.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-03</Date><Taux>86.3083523461</Taux><PonctuelParRetard>6.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-07</Date><Taux>85.2</Taux><PonctuelParRetard>5.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-11</Date><Taux>76.9</Taux><PonctuelParRetard>3.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-03</Date><Taux>87.9</Taux><PonctuelParRetard>7.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-04</Date><Taux>88.5</Taux><PonctuelParRetard>7.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-06</Date><Taux>85.2</Taux><PonctuelParRetard>5.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-11</Date><Taux>84.7789019644</Taux><PonctuelParRetard>5.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-12</Date><Taux>84.2</Taux><PonctuelParRetard>5.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-04</Date><Taux>86.5549619436</Taux><PonctuelParRetard>6.4</PonctuelParRetard></Ponctualite></Ponctualites></Train></Ligne><Ligne><ID>E</ID><Nom>RER E</Nom><Train><ID>TRA_5</ID><Ponctualites><Entete><Date>Date</Date><Taux>Taux de ponctualité</Taux><PonctuelParRetard>Nombre de voyageurs à l'heure pour un voyageur en retard</PonctuelParRetard></Entete><Ponctualite><Date>2013-05</Date><Taux>95.5</Taux><PonctuelParRetard>21.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-08</Date><Taux>95.4</Taux><PonctuelParRetard>20.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-09</Date><Taux>96.8</Taux><PonctuelParRetard>30.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-11</Date><Taux>92.0</Taux><PonctuelParRetard>11.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-01</Date><Taux>93.6</Taux><PonctuelParRetard>14.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-10</Date><Taux>94.0</Taux><PonctuelParRetard>15.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-03</Date><Taux>96.3263168075</Taux><PonctuelParRetard>26.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-02</Date><Taux>94.7</Taux><PonctuelParRetard>17.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-02</Date><Taux>95.0</Taux><PonctuelParRetard>19.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-04</Date><Taux>93.9</Taux><PonctuelParRetard>15.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-06</Date><Taux>95.4</Taux><PonctuelParRetard>20.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-05</Date><Taux>95.9872926887</Taux><PonctuelParRetard>23.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-08</Date><Taux>94.7</Taux><PonctuelParRetard>17.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-01</Date><Taux>93.3</Taux><PonctuelParRetard>13.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-03</Date><Taux>92.9</Taux><PonctuelParRetard>13.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-07</Date><Taux>94.0</Taux><PonctuelParRetard>15.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-10</Date><Taux>95.2</Taux><PonctuelParRetard>19.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-12</Date><Taux>94.9</Taux><PonctuelParRetard>18.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-03</Date><Taux>94.4</Taux><PonctuelParRetard>16.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-05</Date><Taux>93.3</Taux><PonctuelParRetard>13.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-09</Date><Taux>96.0</Taux><PonctuelParRetard>24.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-04</Date><Taux>90.539314526</Taux><PonctuelParRetard>9.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-07</Date><Taux>93.5</Taux><PonctuelParRetard>14.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-04</Date><Taux>96.2</Taux><PonctuelParRetard>25.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-06</Date><Taux>93.9</Taux><PonctuelParRetard>15.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-07</Date><Taux>92.5</Taux><PonctuelParRetard>12.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-08</Date><Taux>96.0</Taux><PonctuelParRetard>24.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-11</Date><Taux>95.6646036773</Taux><PonctuelParRetard>22.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-12</Date><Taux>92.7</Taux><PonctuelParRetard>12.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-01</Date><Taux>94.9052094942</Taux><PonctuelParRetard>18.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-02</Date><Taux>94.0738560337</Taux><PonctuelParRetard>15.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-06</Date><Taux>93.059152876</Taux><PonctuelParRetard>13.4</PonctuelParRetard></Ponctualite></Ponctualites></Train></Ligne><Ligne><ID>C</ID><Nom>RER C</Nom><Train><ID>TRA_3</ID><Ponctualites><Entete><Date>Date</Date><Taux>Taux de ponctualité</Taux><PonctuelParRetard>Nombre de voyageurs à l'heure pour un voyageur en retard</PonctuelParRetard></Entete><Ponctualite><Date>2014-05</Date><Taux>91.7</Taux><PonctuelParRetard>11.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-08</Date><Taux>93.9</Taux><PonctuelParRetard>15.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-12</Date><Taux>89.3</Taux><PonctuelParRetard>8.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-02</Date><Taux>91.8</Taux><PonctuelParRetard>11.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-08</Date><Taux>93.4</Taux><PonctuelParRetard>14.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-06</Date><Taux>87.3</Taux><PonctuelParRetard>6.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-10</Date><Taux>84.1</Taux><PonctuelParRetard>5.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-02</Date><Taux>91.6087087474</Taux><PonctuelParRetard>10.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-03</Date><Taux>88.9155867451</Taux><PonctuelParRetard>8.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-07</Date><Taux>88.3</Taux><PonctuelParRetard>7.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-06</Date><Taux>90.3</Taux><PonctuelParRetard>9.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-11</Date><Taux>85.5</Taux><PonctuelParRetard>5.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-02</Date><Taux>90.8</Taux><PonctuelParRetard>9.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-09</Date><Taux>92.9</Taux><PonctuelParRetard>13.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-01</Date><Taux>91.4032715394</Taux><PonctuelParRetard>10.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-05</Date><Taux>91.4447374589</Taux><PonctuelParRetard>10.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-06</Date><Taux>86.1727621706</Taux><PonctuelParRetard>6.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-05</Date><Taux>92.3</Taux><PonctuelParRetard>12.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-07</Date><Taux>90.8</Taux><PonctuelParRetard>9.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-12</Date><Taux>90.9</Taux><PonctuelParRetard>10.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-11</Date><Taux>86.7347499119</Taux><PonctuelParRetard>6.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-08</Date><Taux>93.1</Taux><PonctuelParRetard>13.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-01</Date><Taux>91.9</Taux><PonctuelParRetard>11.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-03</Date><Taux>87.6</Taux><PonctuelParRetard>7.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-04</Date><Taux>88.7</Taux><PonctuelParRetard>7.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-09</Date><Taux>93.1</Taux><PonctuelParRetard>13.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-10</Date><Taux>85.6</Taux><PonctuelParRetard>5.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-01</Date><Taux>91.4</Taux><PonctuelParRetard>10.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-03</Date><Taux>91.5</Taux><PonctuelParRetard>10.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-04</Date><Taux>91.6</Taux><PonctuelParRetard>10.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-07</Date><Taux>83.9</Taux><PonctuelParRetard>5.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-04</Date><Taux>89.2820641654</Taux><PonctuelParRetard>8.3</PonctuelParRetard></Ponctualite></Ponctualites></Train></Ligne></Lignes></Service><Service><Nom>Transilien</Nom><Lignes><Ligne><ID>H</ID><Nom>Paris Nord Ouest</Nom><Train><ID>TRA_6</ID><Ponctualites><Entete><Date>Date</Date><Taux>Taux de ponctualité</Taux><PonctuelParRetard>Nombre de voyageurs à l'heure pour un voyageur en retard</PonctuelParRetard></Entete><Ponctualite><Date>2013-02</Date><Taux>92.7</Taux><PonctuelParRetard>12.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-03</Date><Taux>92.3</Taux><PonctuelParRetard>12.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-04</Date><Taux>94.6</Taux><PonctuelParRetard>17.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-01</Date><Taux>95.9</Taux><PonctuelParRetard>23.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-04</Date><Taux>95.7</Taux><PonctuelParRetard>22.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-05</Date><Taux>96.9</Taux><PonctuelParRetard>31.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-05</Date><Taux>95.9381245311</Taux><PonctuelParRetard>23.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-07</Date><Taux>92.8</Taux><PonctuelParRetard>12.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-02</Date><Taux>96.1</Taux><PonctuelParRetard>24.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-11</Date><Taux>94.7480048369</Taux><PonctuelParRetard>18.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-12</Date><Taux>94.1</Taux><PonctuelParRetard>15.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-01</Date><Taux>95.5645619782</Taux><PonctuelParRetard>21.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-03</Date><Taux>96.0638677623</Taux><PonctuelParRetard>24.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-08</Date><Taux>96.3</Taux><PonctuelParRetard>26.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-06</Date><Taux>94.1</Taux><PonctuelParRetard>15.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-12</Date><Taux>94.7</Taux><PonctuelParRetard>17.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-03</Date><Taux>96.4</Taux><PonctuelParRetard>26.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-04</Date><Taux>95.0794493186</Taux><PonctuelParRetard>19.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-06</Date><Taux>92.3224849552</Taux><PonctuelParRetard>12.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-05</Date><Taux>95.9</Taux><PonctuelParRetard>23.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-08</Date><Taux>95.4</Taux><PonctuelParRetard>20.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-01</Date><Taux>93.9</Taux><PonctuelParRetard>15.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-07</Date><Taux>94.4</Taux><PonctuelParRetard>16.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-09</Date><Taux>95.4</Taux><PonctuelParRetard>20.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-10</Date><Taux>94.2</Taux><PonctuelParRetard>16.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-11</Date><Taux>93.1</Taux><PonctuelParRetard>13.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-06</Date><Taux>93.9</Taux><PonctuelParRetard>15.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-07</Date><Taux>93.1</Taux><PonctuelParRetard>13.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-08</Date><Taux>95.5</Taux><PonctuelParRetard>21.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-09</Date><Taux>96.3</Taux><PonctuelParRetard>26.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-10</Date><Taux>93.7</Taux><PonctuelParRetard>14.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-02</Date><Taux>94.1782150702</Taux><PonctuelParRetard>16.2</PonctuelParRetard></Ponctualite></Ponctualites></Train></Ligne><Ligne><ID>K</ID><Nom>Paris Nord Crépy</Nom><Train><ID>TRA_8</ID><Ponctualites><Entete><Date>Date</Date><Taux>Taux de ponctualité</Taux><PonctuelParRetard>Nombre de voyageurs à l'heure pour un voyageur en retard</PonctuelParRetard></Entete><Ponctualite><Date>2013-02</Date><Taux>75.2</Taux><PonctuelParRetard>3.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-03</Date><Taux>77.3</Taux><PonctuelParRetard>3.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-05</Date><Taux>81.3</Taux><PonctuelParRetard>4.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-01</Date><Taux>76.6</Taux><PonctuelParRetard>3.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-02</Date><Taux>84.4</Taux><PonctuelParRetard>5.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-06</Date><Taux>79.6</Taux><PonctuelParRetard>3.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-06</Date><Taux>90.0426262557</Taux><PonctuelParRetard>9.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-08</Date><Taux>87.6</Taux><PonctuelParRetard>7.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-06</Date><Taux>71.9</Taux><PonctuelParRetard>2.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-07</Date><Taux>85.1</Taux><PonctuelParRetard>5.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-03</Date><Taux>87.9</Taux><PonctuelParRetard>7.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-01</Date><Taux>87.1798892246</Taux><PonctuelParRetard>6.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-03</Date><Taux>88.1187031039</Taux><PonctuelParRetard>7.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-04</Date><Taux>82.0</Taux><PonctuelParRetard>4.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-10</Date><Taux>81.2</Taux><PonctuelParRetard>4.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-04</Date><Taux>87.0</Taux><PonctuelParRetard>6.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-07</Date><Taux>87.6</Taux><PonctuelParRetard>7.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-09</Date><Taux>92.1</Taux><PonctuelParRetard>11.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-10</Date><Taux>86.5</Taux><PonctuelParRetard>6.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-01</Date><Taux>75.2</Taux><PonctuelParRetard>3.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-09</Date><Taux>86.0</Taux><PonctuelParRetard>6.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-11</Date><Taux>77.7</Taux><PonctuelParRetard>3.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-12</Date><Taux>83.1</Taux><PonctuelParRetard>4.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-05</Date><Taux>91.9</Taux><PonctuelParRetard>11.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-11</Date><Taux>84.5732734419</Taux><PonctuelParRetard>5.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-02</Date><Taux>85.0869749682</Taux><PonctuelParRetard>5.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-05</Date><Taux>91.3842125718</Taux><PonctuelParRetard>10.6</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-08</Date><Taux>88.3</Taux><PonctuelParRetard>7.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-08</Date><Taux>91.3</Taux><PonctuelParRetard>10.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-12</Date><Taux>83.6</Taux><PonctuelParRetard>5.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-04</Date><Taux>86.184744626</Taux><PonctuelParRetard>6.2</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-07</Date><Taux>89.4</Taux><PonctuelParRetard>8.4</PonctuelParRetard></Ponctualite></Ponctualites></Train></Ligne><Ligne><ID>P</ID><Nom>Paris Est</Nom><Train><ID>TRA_11</ID><Ponctualites><Entete><Date>Date</Date><Taux>Taux de ponctualité</Taux><PonctuelParRetard>Nombre de voyageurs à l'heure pour un voyageur en retard</PonctuelParRetard></Entete><Ponctualite><Date>2013-02</Date><Taux>89.4</Taux><PonctuelParRetard>8.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-05</Date><Taux>90.4</Taux><PonctuelParRetard>9.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-09</Date><Taux>88.0</Taux><PonctuelParRetard>7.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-11</Date><Taux>82.8</Taux><PonctuelParRetard>4.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-04</Date><Taux>87.9</Taux><PonctuelParRetard>7.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-11</Date><Taux>87.2800648893</Taux><PonctuelParRetard>6.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-12</Date><Taux>88.7</Taux><PonctuelParRetard>7.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-06</Date><Taux>89.4</Taux><PonctuelParRetard>8.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-03</Date><Taux>89.0</Taux><PonctuelParRetard>8.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-08</Date><Taux>92.1</Taux><PonctuelParRetard>11.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-12</Date><Taux>91.0</Taux><PonctuelParRetard>10.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-08</Date><Taux>92.6</Taux><PonctuelParRetard>12.5</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-09</Date><Taux>93.5</Taux><PonctuelParRetard>14.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-01</Date><Taux>90.9493380196</Taux><PonctuelParRetard>10.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-03</Date><Taux>93.2541415409</Taux><PonctuelParRetard>13.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-04</Date><Taux>87.9561752108</Taux><PonctuelParRetard>7.3</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-05</Date><Taux>92.7029222345</Taux><PonctuelParRetard>12.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-06</Date><Taux>88.8351116319</Taux><PonctuelParRetard>8.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-08</Date><Taux>90.8</Taux><PonctuelParRetard>9.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-07</Date><Taux>90.1</Taux><PonctuelParRetard>9.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-01</Date><Taux>91.0</Taux><PonctuelParRetard>10.1</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-03</Date><Taux>88.8</Taux><PonctuelParRetard>7.9</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-05</Date><Taux>92.7</Taux><PonctuelParRetard>12.7</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-06</Date><Taux>89.4</Taux><PonctuelParRetard>8.4</PonctuelParRetard></Ponctualite><Ponctualite><Date>2014-10</Date><Taux>90.7</Taux><PonctuelParRetard>9.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2015-02</Date><Taux>92.7710751127</Taux><PonctuelParRetard>12.8</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-01</Date><Taux>85.8</Taux><PonctuelParRetard>6.0</PonctuelParRetard></Ponctualite><Ponctualite><Date>2013-04</Date><Taux>92.7</Taux><P